### ISSUE TITLE
Iterate over attributes

### ISSUE THREAD

**Issue by davewarn** [y21/tl#16]
Is it possible to iterate over the attributes of a HTMLTag? I couldn't find a way to do this. Sorry if I missed it!

**Comment by y21** [comment]
I've just published a new version that adds [`Attributes::iter`](https://docs.rs/tl/0.5.0/tl/struct.Attributes.html#method.iter):
```rs
fn main() {
    let input = r#"<p id="test" a="b" c="d" e="f" g="hi">hello world</p>"#;

    let dom = tl::parse(input, Default::default()).unwrap();
    let parser = dom.parser();

    let element = dom.get_element_by_id("test")
        .unwrap()
        .get(parser)
        .unwrap()
        .as_tag()
        .unwrap();

    for (key, value) in element.attributes().iter() {
        println!("{}: {}", key, value.as_deref().unwrap_or_default());
    }
}
```
```
     Running `target/debug/tltest`
a: b
c: d
e: f
g: hi
id: test
```
Let me know if that helped.

**Comment by davewarn** [comment]
This works perfectly. Thank you so much!

I really like this library. It is super fast, lightweight, and builds quickly. Thank you for sharing it with everyone!
