### ISSUE TITLE
Relax `Attributes::insert`

### ISSUE THREAD

**Issue by oovm** [y21/tl#27]
- [x] It is a breaking change

I think this api is too restricted.

https://github.com/y21/tl/blob/27e88119b622b64a26c6e690c571fd8ebed0dc32/src/parser/tag.rs#L94-L96

for example:

```rust
let style = "some style".to_string();
attributes.insert("style", Some(style))
```

this is not possible.

```rust
let mut style = Bytes::new();
style.set("some style").unwrap().unwrap();
attributes.insert("style", Some(style));
```

Also not possible.

---

At least the same type of restrictions on K, V should be lifted.

that is

```rust
 pub fn insert<K, V>(&mut self, key: K, value: Option<V>) 
 where 
     K: Into<Bytes<'a>>, 
     V: Into<Bytes<'a>>, 
```

or

```rust
 pub fn insert<K, V>(&mut self, key: K, value: Option<V>) 
 where 
     K: IntoOwnedBytes, 
     V: IntoOwnedBytes, 
```

**Comment by y21** [comment]
Published a new version that changes the function signature to take two generic parameters `(K, V)`, so the key and value types can differ now. I've also added a `TryFrom<String> for Bytes` implementation, so you can write
```rs
let style = "some style".to_string();
attributes.insert("style", Some(Bytes::try_from(style).unwrap()));
```
