### ISSUE TITLE
Isn't HTMLTag#inner_html actually an outer_html?

### ISSUE THREAD

**Issue by kelko** [y21/tl#39]
The method `pub fn inner_html<'p>(&'p self, parser: &'p Parser<'a>) -> String {` on `HTMLTag` states in the documentation that it is equivalent to `Element#innerHTML` in browser. Also the name implies this.
The [referenced MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) defines innerHTML as:

> A string containing the HTML serialization of the element's __descendants__. 

Now the implementation of `inner_html` also serialises the element itself including all the attributes. This seems to me more closely to the definition of [Element#outerHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML):

> Reading the value of outerHTML returns a string containing an HTML serialization of __the element__ _and_ its descendants. 

I prefer having the outerHTML-equivalent implementation, but maybe the name of the method should be corrected.

**Comment by y21** [comment]
Good point. Yes you are right. 😅

**Comment by y21** [comment]
Published a new version on crates.io that fixes this. `{Node, HTMLTag}::inner_html` now only returns the markup of the contained elements and `{Node, HTMLTag}::outer_html` will now do what `Node::inner_html` did before.
