### ISSUE TITLE
query_selector cannot parse meta[property=og:title]

### ISSUE THREAD

**Issue by mehmetcansahin** [y21/tl#46]
Hi,
I cannot parse meta[property=og:title]. But alternatively I found this solution meta[property*=title]. What could I be doing wrong?

```
let node_option = self
            .dom
            .query_selector("meta[property=og:title]") or .query_selector(r#"meta[property="og:title"]"#)
            .and_then(|mut iter| iter.next());
```

**Comment by kelko** [comment]
As I took a look at that code not long ago, allow me to share some info: The parser for CSS selectors currently only accepts a sub-set of characters as attribute value:

```rust
let value = self.read_identifier();
```
[Source](https://github.com/y21/tl/blob/master/src/queryselector/parser.rs#L93)

`read_identifier` checks if the value `is_ident`, which itself is defined as
```rust
pub fn is_ident(c: u8) -> bool {
    (b'0'..=b'9').contains(&c)
        || (b'A'..=b'Z').contains(&c)
        || (b'a'..=b'z').contains(&c)
        || c == b'-'
        || c == b'_'
}
```
[Source](https://github.com/y21/tl/blob/master/src/util.rs)

So the `:` is currently not accepted.

**Comment by y21** [comment]
afaik `meta[property=og:title]` isn't valid, however `meta[property="og:title"]` should work, but as @kelko pointed out the query selector only accepts identifiers right now. I think for this it makes sense to do what the HTML parser does for parsing attributes, and check if the value starts with " or ', and if it does, keep reading until it finds that quote. Only if it doesn't, read an identifier

**Comment by mehmetcansahin** [comment]
thanks @y21 and @kelko.
